// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from MessageType.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlVHlwZS5wcm90bxIIcHJvdG9idWYqdQoJUGxhY2VUeXBlEhMK",
            "D05VTExfUExBQ0VfVFlQRRAAEggKBEhPTUUQARIJCgVTUEFDRRACEggKBFJV",
            "SU4QAxIKCgZTSEFET1cQBBIMCghBU1RFUk9JRBAFEgwKCFJFU09VUkNFEAYS",
            "DAoIQlVJTERJTkcQByptCg1Db2xsZWN0b3JUeXBlEhcKE05VTExfQ09MTEVD",
            "VE9SX1RZUEUQABITCg9CQVNJQ19DT0xMRUNUT1IQARIWChJBRFZBTkNFRF9D",
            "T0xMRUNUT1IQAhIWChJVTFRJTUFURV9DT0xMRUNUT1IQAypZCglBcm1vclR5",
            "cGUSEwoPTlVMTF9BUk1PUl9UWVBFEAASDwoLQkFTSUNfQVJNT1IQARISCg5B",
            "RFZBTkNFRF9BUk1PUhACEhIKDlVMVElNQVRFX0FSTU9SEAMqXgoKU2hpZWxk",
            "VHlwZRIUChBOVUxMX1NISUVMRF9UWVBFEAASEAoMQkFTSUNfU0hJRUxEEAES",
            "EwoPQURWQU5DRURfU0hJRUxEEAISEwoPVUxUSU1BVEVfU0hJRUxEEAMqYwoL",
            "QnVpbGRlclR5cGUSFQoRTlVMTF9CVUlMREVSX1RZUEUQABIRCg1CQVNJQ19C",
            "VUlMREVSEAESFAoQQURWQU5DRURfQlVJTERFUhACEhQKEFVMVElNQVRFX0JV",
            "SUxERVIQAypjCgpCdWxsZXRUeXBlEhQKEE5VTExfQlVMTEVUX1RZUEUQABIJ",
            "CgVMQVNFUhABEgoKBlBMQVNNQRACEgkKBVNIRUxMEAMSCwoHTUlTU0lMRRAE",
            "EhAKDEVMRUNUUklDX0FSQxAFKpABCglTaGlwU3RhdGUSDwoLTlVMTF9TVEFU",
            "VVMQABIICgRJRExFEAESDQoJUFJPRFVDSU5HEAISEAoMQ09OU1RSVUNUSU5H",
            "EAMSDgoKUkVDT1ZFUklORxAEEg0KCVJFQ1lDTElORxAFEg0KCUFUVEFDS0lO",
            "RxAGEgwKCFNXSU5HSU5HEAcSCwoHU1RVTk5FRBAIKl4KDEJ1aWxkaW5nVHlw",
            "ZRIWChJOVUxMX0JVSUxESU5HX1RZUEUQABILCgdGQUNUT1JZEAESDQoJQ09N",
            "TVVOSVRZEAISDAoIRk9SVFJFU1MQAxIMCghXT1JNSE9MRRAEKlMKCFNoaXBU",
            "eXBlEhIKDk5VTExfU0hJUF9UWVBFEAASEQoNQ0lWSUxJQU5fU0hJUBABEhEK",
            "DU1JTElUQVJZX1NISVAQAhINCglGTEFHX1NISVAQAyotCgpQbGF5ZXJUZWFt",
            "Eg0KCU5VTExfVEVBTRAAEgYKAlVQEAESCAoERE9XThACKlAKCUdhbWVTdGF0",
            "ZRITCg9OVUxMX0dBTUVfU1RBVEUQABIOCgpHQU1FX1NUQVJUEAESEAoMR0FN",
            "RV9SVU5OSU5HEAISDAoIR0FNRV9FTkQQA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.PlaceType), typeof(global::Protobuf.CollectorType), typeof(global::Protobuf.ArmorType), typeof(global::Protobuf.ShieldType), typeof(global::Protobuf.BuilderType), typeof(global::Protobuf.BulletType), typeof(global::Protobuf.ShipState), typeof(global::Protobuf.BuildingType), typeof(global::Protobuf.ShipType), typeof(global::Protobuf.PlayerTeam), typeof(global::Protobuf.GameState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PlaceType {
    [pbr::OriginalName("NULL_PLACE_TYPE")] NullPlaceType = 0,
    [pbr::OriginalName("HOME")] Home = 1,
    [pbr::OriginalName("SPACE")] Space = 2,
    [pbr::OriginalName("RUIN")] Ruin = 3,
    [pbr::OriginalName("SHADOW")] Shadow = 4,
    [pbr::OriginalName("ASTEROID")] Asteroid = 5,
    [pbr::OriginalName("RESOURCE")] Resource = 6,
    [pbr::OriginalName("BUILDING")] Building = 7,
  }

  public enum CollectorType {
    [pbr::OriginalName("NULL_COLLECTOR_TYPE")] NullCollectorType = 0,
    [pbr::OriginalName("BASIC_COLLECTOR")] BasicCollector = 1,
    [pbr::OriginalName("ADVANCED_COLLECTOR")] AdvancedCollector = 2,
    [pbr::OriginalName("ULTIMATE_COLLECTOR")] UltimateCollector = 3,
  }

  public enum ArmorType {
    [pbr::OriginalName("NULL_ARMOR_TYPE")] NullArmorType = 0,
    [pbr::OriginalName("BASIC_ARMOR")] BasicArmor = 1,
    [pbr::OriginalName("ADVANCED_ARMOR")] AdvancedArmor = 2,
    [pbr::OriginalName("ULTIMATE_ARMOR")] UltimateArmor = 3,
  }

  public enum ShieldType {
    [pbr::OriginalName("NULL_SHIELD_TYPE")] NullShieldType = 0,
    [pbr::OriginalName("BASIC_SHIELD")] BasicShield = 1,
    [pbr::OriginalName("ADVANCED_SHIELD")] AdvancedShield = 2,
    [pbr::OriginalName("ULTIMATE_SHIELD")] UltimateShield = 3,
  }

  public enum BuilderType {
    [pbr::OriginalName("NULL_BUILDER_TYPE")] NullBuilderType = 0,
    [pbr::OriginalName("BASIC_BUILDER")] BasicBuilder = 1,
    [pbr::OriginalName("ADVANCED_BUILDER")] AdvancedBuilder = 2,
    [pbr::OriginalName("ULTIMATE_BUILDER")] UltimateBuilder = 3,
  }

  public enum BulletType {
    [pbr::OriginalName("NULL_BULLET_TYPE")] NullBulletType = 0,
    [pbr::OriginalName("LASER")] Laser = 1,
    [pbr::OriginalName("PLASMA")] Plasma = 2,
    [pbr::OriginalName("SHELL")] Shell = 3,
    [pbr::OriginalName("MISSILE")] Missile = 4,
    [pbr::OriginalName("ELECTRIC_ARC")] ElectricArc = 5,
  }

  public enum ShipState {
    [pbr::OriginalName("NULL_STATUS")] NullStatus = 0,
    [pbr::OriginalName("IDLE")] Idle = 1,
    [pbr::OriginalName("PRODUCING")] Producing = 2,
    [pbr::OriginalName("CONSTRUCTING")] Constructing = 3,
    [pbr::OriginalName("RECOVERING")] Recovering = 4,
    [pbr::OriginalName("RECYCLING")] Recycling = 5,
    [pbr::OriginalName("ATTACKING")] Attacking = 6,
    [pbr::OriginalName("SWINGING")] Swinging = 7,
    [pbr::OriginalName("STUNNED")] Stunned = 8,
  }

  public enum BuildingType {
    [pbr::OriginalName("NULL_BUILDING_TYPE")] NullBuildingType = 0,
    [pbr::OriginalName("FACTORY")] Factory = 1,
    [pbr::OriginalName("COMMUNITY")] Community = 2,
    [pbr::OriginalName("FORTRESS")] Fortress = 3,
    [pbr::OriginalName("WORMHOLE")] Wormhole = 4,
  }

  public enum ShipType {
    [pbr::OriginalName("NULL_SHIP_TYPE")] NullShipType = 0,
    [pbr::OriginalName("CIVILIAN_SHIP")] CivilianShip = 1,
    [pbr::OriginalName("MILITARY_SHIP")] MilitaryShip = 2,
    [pbr::OriginalName("FLAG_SHIP")] FlagShip = 3,
  }

  public enum PlayerTeam {
    [pbr::OriginalName("NULL_TEAM")] NullTeam = 0,
    [pbr::OriginalName("UP")] Up = 1,
    [pbr::OriginalName("DOWN")] Down = 2,
  }

  /// <summary>
  /// 游戏进行状态
  /// </summary>
  public enum GameState {
    [pbr::OriginalName("NULL_GAME_STATE")] NullGameState = 0,
    [pbr::OriginalName("GAME_START")] GameStart = 1,
    [pbr::OriginalName("GAME_RUNNING")] GameRunning = 2,
    [pbr::OriginalName("GAME_END")] GameEnd = 3,
  }

  #endregion

}

#endregion Designer generated code
