// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protobuf {
  public static partial class AvailableService
  {
    static readonly string __ServiceName = "protobuf.AvailableService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.IDMsg> __Marshaller_protobuf_IDMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.IDMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.BoolRes> __Marshaller_protobuf_BoolRes = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.BoolRes.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.ShipMsg> __Marshaller_protobuf_ShipMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.ShipMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.MessageToClient> __Marshaller_protobuf_MessageToClient = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.MessageToClient.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.HomeMsg> __Marshaller_protobuf_HomeMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.HomeMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.BuildingMsg> __Marshaller_protobuf_BuildingMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.BuildingMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.MoveMsg> __Marshaller_protobuf_MoveMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.MoveMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.MoveRes> __Marshaller_protobuf_MoveRes = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.MoveRes.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.CollectorMsg> __Marshaller_protobuf_CollectorMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.CollectorMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.ArmorMsg> __Marshaller_protobuf_ArmorMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.ArmorMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.ShieldMsg> __Marshaller_protobuf_ShieldMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.ShieldMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.BuilderMsg> __Marshaller_protobuf_BuilderMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.BuilderMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.BulleterMsg> __Marshaller_protobuf_BulleterMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.BulleterMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.SendMsg> __Marshaller_protobuf_SendMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.SendMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.BuildMsg> __Marshaller_protobuf_BuildMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.BuildMsg.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Protobuf.AttackMsg> __Marshaller_protobuf_AttackMsg = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Protobuf.AttackMsg.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes> __Method_TryConnection = new grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TryConnection",
        __Marshaller_protobuf_IDMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.ShipMsg, global::Protobuf.MessageToClient> __Method_AddBasicShip = new grpc::Method<global::Protobuf.ShipMsg, global::Protobuf.MessageToClient>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "AddBasicShip",
        __Marshaller_protobuf_ShipMsg,
        __Marshaller_protobuf_MessageToClient);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.HomeMsg, global::Protobuf.MessageToClient> __Method_AddHome = new grpc::Method<global::Protobuf.HomeMsg, global::Protobuf.MessageToClient>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "AddHome",
        __Marshaller_protobuf_HomeMsg,
        __Marshaller_protobuf_MessageToClient);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.BuildingMsg, global::Protobuf.MessageToClient> __Method_AddBuilding = new grpc::Method<global::Protobuf.BuildingMsg, global::Protobuf.MessageToClient>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "AddBuilding",
        __Marshaller_protobuf_BuildingMsg,
        __Marshaller_protobuf_MessageToClient);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.MoveMsg, global::Protobuf.MoveRes> __Method_Move = new grpc::Method<global::Protobuf.MoveMsg, global::Protobuf.MoveRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Move",
        __Marshaller_protobuf_MoveMsg,
        __Marshaller_protobuf_MoveRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.CollectorMsg, global::Protobuf.BoolRes> __Method_InstallCollectorModule = new grpc::Method<global::Protobuf.CollectorMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InstallCollectorModule",
        __Marshaller_protobuf_CollectorMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.ArmorMsg, global::Protobuf.BoolRes> __Method_InstallArmorModule = new grpc::Method<global::Protobuf.ArmorMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InstallArmorModule",
        __Marshaller_protobuf_ArmorMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.ShieldMsg, global::Protobuf.BoolRes> __Method_InstallShieldModule = new grpc::Method<global::Protobuf.ShieldMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InstallShieldModule",
        __Marshaller_protobuf_ShieldMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.BuilderMsg, global::Protobuf.BoolRes> __Method_InstallBuilderModule = new grpc::Method<global::Protobuf.BuilderMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InstallBuilderModule",
        __Marshaller_protobuf_BuilderMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.BulleterMsg, global::Protobuf.BoolRes> __Method_InstallBulletModule = new grpc::Method<global::Protobuf.BulleterMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InstallBulletModule",
        __Marshaller_protobuf_BulleterMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.SendMsg, global::Protobuf.BoolRes> __Method_SendMessage = new grpc::Method<global::Protobuf.SendMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendMessage",
        __Marshaller_protobuf_SendMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes> __Method_StartRecovering = new grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartRecovering",
        __Marshaller_protobuf_IDMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes> __Method_StartProducing = new grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartProducing",
        __Marshaller_protobuf_IDMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes> __Method_StartRecycling = new grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartRecycling",
        __Marshaller_protobuf_IDMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.BuildMsg, global::Protobuf.BoolRes> __Method_StartBuilding = new grpc::Method<global::Protobuf.BuildMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartBuilding",
        __Marshaller_protobuf_BuildMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.AttackMsg, global::Protobuf.BoolRes> __Method_Attack = new grpc::Method<global::Protobuf.AttackMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Attack",
        __Marshaller_protobuf_AttackMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.BuildMsg, global::Protobuf.BoolRes> __Method_BuildShip = new grpc::Method<global::Protobuf.BuildMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BuildShip",
        __Marshaller_protobuf_BuildMsg,
        __Marshaller_protobuf_BoolRes);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes> __Method_EndAllAction = new grpc::Method<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "EndAllAction",
        __Marshaller_protobuf_IDMsg,
        __Marshaller_protobuf_BoolRes);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protobuf.ServicesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AvailableService</summary>
    [grpc::BindServiceMethod(typeof(AvailableService), "BindService")]
    public abstract partial class AvailableServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> TryConnection(global::Protobuf.IDMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 游戏开局调用一次的服务
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task AddBasicShip(global::Protobuf.ShipMsg request, grpc::IServerStreamWriter<global::Protobuf.MessageToClient> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task AddHome(global::Protobuf.HomeMsg request, grpc::IServerStreamWriter<global::Protobuf.MessageToClient> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task AddBuilding(global::Protobuf.BuildingMsg request, grpc::IServerStreamWriter<global::Protobuf.MessageToClient> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 游戏过程中玩家执行操作的服务   
      ///船动作
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.MoveRes> Move(global::Protobuf.MoveMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> InstallCollectorModule(global::Protobuf.CollectorMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> InstallArmorModule(global::Protobuf.ArmorMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> InstallShieldModule(global::Protobuf.ShieldMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> InstallBuilderModule(global::Protobuf.BuilderMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> InstallBulletModule(global::Protobuf.BulleterMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> SendMessage(global::Protobuf.SendMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// rpc GetMessage (IDMsg) returns (stream MsgRes);
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> StartRecovering(global::Protobuf.IDMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> StartProducing(global::Protobuf.IDMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> StartRecycling(global::Protobuf.IDMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> StartBuilding(global::Protobuf.BuildMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 攻击
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> Attack(global::Protobuf.AttackMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///建筑动作
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> BuildShip(global::Protobuf.BuildMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 结束所有动作
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Protobuf.BoolRes> EndAllAction(global::Protobuf.IDMsg request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AvailableServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_TryConnection, serviceImpl.TryConnection)
          .AddMethod(__Method_AddBasicShip, serviceImpl.AddBasicShip)
          .AddMethod(__Method_AddHome, serviceImpl.AddHome)
          .AddMethod(__Method_AddBuilding, serviceImpl.AddBuilding)
          .AddMethod(__Method_Move, serviceImpl.Move)
          .AddMethod(__Method_InstallCollectorModule, serviceImpl.InstallCollectorModule)
          .AddMethod(__Method_InstallArmorModule, serviceImpl.InstallArmorModule)
          .AddMethod(__Method_InstallShieldModule, serviceImpl.InstallShieldModule)
          .AddMethod(__Method_InstallBuilderModule, serviceImpl.InstallBuilderModule)
          .AddMethod(__Method_InstallBulletModule, serviceImpl.InstallBulletModule)
          .AddMethod(__Method_SendMessage, serviceImpl.SendMessage)
          .AddMethod(__Method_StartRecovering, serviceImpl.StartRecovering)
          .AddMethod(__Method_StartProducing, serviceImpl.StartProducing)
          .AddMethod(__Method_StartRecycling, serviceImpl.StartRecycling)
          .AddMethod(__Method_StartBuilding, serviceImpl.StartBuilding)
          .AddMethod(__Method_Attack, serviceImpl.Attack)
          .AddMethod(__Method_BuildShip, serviceImpl.BuildShip)
          .AddMethod(__Method_EndAllAction, serviceImpl.EndAllAction).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AvailableServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_TryConnection, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(serviceImpl.TryConnection));
      serviceBinder.AddMethod(__Method_AddBasicShip, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Protobuf.ShipMsg, global::Protobuf.MessageToClient>(serviceImpl.AddBasicShip));
      serviceBinder.AddMethod(__Method_AddHome, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Protobuf.HomeMsg, global::Protobuf.MessageToClient>(serviceImpl.AddHome));
      serviceBinder.AddMethod(__Method_AddBuilding, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Protobuf.BuildingMsg, global::Protobuf.MessageToClient>(serviceImpl.AddBuilding));
      serviceBinder.AddMethod(__Method_Move, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.MoveMsg, global::Protobuf.MoveRes>(serviceImpl.Move));
      serviceBinder.AddMethod(__Method_InstallCollectorModule, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.CollectorMsg, global::Protobuf.BoolRes>(serviceImpl.InstallCollectorModule));
      serviceBinder.AddMethod(__Method_InstallArmorModule, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.ArmorMsg, global::Protobuf.BoolRes>(serviceImpl.InstallArmorModule));
      serviceBinder.AddMethod(__Method_InstallShieldModule, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.ShieldMsg, global::Protobuf.BoolRes>(serviceImpl.InstallShieldModule));
      serviceBinder.AddMethod(__Method_InstallBuilderModule, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.BuilderMsg, global::Protobuf.BoolRes>(serviceImpl.InstallBuilderModule));
      serviceBinder.AddMethod(__Method_InstallBulletModule, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.BulleterMsg, global::Protobuf.BoolRes>(serviceImpl.InstallBulletModule));
      serviceBinder.AddMethod(__Method_SendMessage, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.SendMsg, global::Protobuf.BoolRes>(serviceImpl.SendMessage));
      serviceBinder.AddMethod(__Method_StartRecovering, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(serviceImpl.StartRecovering));
      serviceBinder.AddMethod(__Method_StartProducing, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(serviceImpl.StartProducing));
      serviceBinder.AddMethod(__Method_StartRecycling, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(serviceImpl.StartRecycling));
      serviceBinder.AddMethod(__Method_StartBuilding, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.BuildMsg, global::Protobuf.BoolRes>(serviceImpl.StartBuilding));
      serviceBinder.AddMethod(__Method_Attack, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.AttackMsg, global::Protobuf.BoolRes>(serviceImpl.Attack));
      serviceBinder.AddMethod(__Method_BuildShip, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.BuildMsg, global::Protobuf.BoolRes>(serviceImpl.BuildShip));
      serviceBinder.AddMethod(__Method_EndAllAction, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protobuf.IDMsg, global::Protobuf.BoolRes>(serviceImpl.EndAllAction));
    }

  }
}
#endregion
