// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from Services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for Services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5TZXJ2aWNlcy5wcm90bxIIcHJvdG9idWYaFU1lc3NhZ2UyQ2xpZW50cy5w",
            "cm90bxoUTWVzc2FnZTJTZXJ2ZXIucHJvdG8ygQUKEEF2YWlsYWJsZVNlcnZp",
            "Y2USMwoNVHJ5Q29ubmVjdGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJvdG9i",
            "dWYuQm9vbFJlcxI9CglBZGRQbGF5ZXISEy5wcm90b2J1Zi5QbGF5ZXJNc2ca",
            "GS5wcm90b2J1Zi5NZXNzYWdlVG9DbGllbnQwARIsCgRNb3ZlEhEucHJvdG9i",
            "dWYuTW92ZU1zZxoRLnByb3RvYnVmLk1vdmVSZXMSLQoHUmVjb3ZlchIPLnBy",
            "b3RvYnVmLklETXNnGhEucHJvdG9idWYuQm9vbFJlcxIxCgdQcm9kdWNlEhMu",
            "cHJvdG9idWYuVGFyZ2V0TXNnGhEucHJvdG9idWYuQm9vbFJlcxI0CgdSZWJ1",
            "aWxkEhYucHJvdG9idWYuQ29uc3RydWN0TXNnGhEucHJvdG9idWYuQm9vbFJl",
            "cxI2CglDb25zdHJ1Y3QSFi5wcm90b2J1Zi5Db25zdHJ1Y3RNc2caES5wcm90",
            "b2J1Zi5Cb29sUmVzEjAKBkF0dGFjaxITLnByb3RvYnVmLkF0dGFja01zZxoR",
            "LnByb3RvYnVmLkJvb2xSZXMSLAoEU2VuZBIRLnByb3RvYnVmLlNlbmRNc2ca",
            "ES5wcm90b2J1Zi5Cb29sUmVzEjgKDUluc3RhbGxNb2R1bGUSFC5wcm90b2J1",
            "Zi5JbnN0YWxsTXNnGhEucHJvdG9idWYuQm9vbFJlcxItCgdSZWN5Y2xlEg8u",
            "cHJvdG9idWYuSURNc2caES5wcm90b2J1Zi5Cb29sUmVzEjIKDEVuZEFsbEFj",
            "dGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJvdG9idWYuQm9vbFJlc2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Message2ClientsReflection.Descriptor, global::Protobuf.Message2ServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
