// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from Services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for Services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5TZXJ2aWNlcy5wcm90bxIIcHJvdG9idWYaFU1lc3NhZ2UyQ2xpZW50cy5w",
            "cm90bxoUTWVzc2FnZTJTZXJ2ZXIucHJvdG8yoAgKEEF2YWlsYWJsZVNlcnZp",
            "Y2USMwoNVHJ5Q29ubmVjdGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJvdG9i",
            "dWYuQm9vbFJlcxI+CgxBZGRCYXNpY1NoaXASES5wcm90b2J1Zi5TaGlwTXNn",
            "GhkucHJvdG9idWYuTWVzc2FnZVRvQ2xpZW50MAESOQoHQWRkSG9tZRIRLnBy",
            "b3RvYnVmLkhvbWVNc2caGS5wcm90b2J1Zi5NZXNzYWdlVG9DbGllbnQwARJB",
            "CgtBZGRCdWlsZGluZxIVLnByb3RvYnVmLkJ1aWxkaW5nTXNnGhkucHJvdG9i",
            "dWYuTWVzc2FnZVRvQ2xpZW50MAESLAoETW92ZRIRLnByb3RvYnVmLk1vdmVN",
            "c2caES5wcm90b2J1Zi5Nb3ZlUmVzEkMKFkluc3RhbGxDb2xsZWN0b3JNb2R1",
            "bGUSFi5wcm90b2J1Zi5Db2xsZWN0b3JNc2caES5wcm90b2J1Zi5Cb29sUmVz",
            "EjsKEkluc3RhbGxBcm1vck1vZHVsZRISLnByb3RvYnVmLkFybW9yTXNnGhEu",
            "cHJvdG9idWYuQm9vbFJlcxI9ChNJbnN0YWxsU2hpZWxkTW9kdWxlEhMucHJv",
            "dG9idWYuU2hpZWxkTXNnGhEucHJvdG9idWYuQm9vbFJlcxI/ChRJbnN0YWxs",
            "QnVpbGRlck1vZHVsZRIULnByb3RvYnVmLkJ1aWxkZXJNc2caES5wcm90b2J1",
            "Zi5Cb29sUmVzEj8KE0luc3RhbGxCdWxsZXRNb2R1bGUSFS5wcm90b2J1Zi5C",
            "dWxsZXRlck1zZxoRLnByb3RvYnVmLkJvb2xSZXMSMwoLU2VuZE1lc3NhZ2US",
            "ES5wcm90b2J1Zi5TZW5kTXNnGhEucHJvdG9idWYuQm9vbFJlcxI1Cg9TdGFy",
            "dFJlY292ZXJpbmcSDy5wcm90b2J1Zi5JRE1zZxoRLnByb3RvYnVmLkJvb2xS",
            "ZXMSNAoOU3RhcnRQcm9kdWNpbmcSDy5wcm90b2J1Zi5JRE1zZxoRLnByb3Rv",
            "YnVmLkJvb2xSZXMSNAoOU3RhcnRSZWN5Y2xpbmcSDy5wcm90b2J1Zi5JRE1z",
            "ZxoRLnByb3RvYnVmLkJvb2xSZXMSNgoNU3RhcnRCdWlsZGluZxISLnByb3Rv",
            "YnVmLkJ1aWxkTXNnGhEucHJvdG9idWYuQm9vbFJlcxIwCgZBdHRhY2sSEy5w",
            "cm90b2J1Zi5BdHRhY2tNc2caES5wcm90b2J1Zi5Cb29sUmVzEjIKCUJ1aWxk",
            "U2hpcBISLnByb3RvYnVmLkJ1aWxkTXNnGhEucHJvdG9idWYuQm9vbFJlcxIy",
            "CgxFbmRBbGxBY3Rpb24SDy5wcm90b2J1Zi5JRE1zZxoRLnByb3RvYnVmLkJv",
            "b2xSZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Message2ClientsReflection.Descriptor, global::Protobuf.Message2ServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
