// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from Services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for Services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5TZXJ2aWNlcy5wcm90bxIIcHJvdG9idWYaFU1lc3NhZ2UyQ2xpZW50cy5w",
            "cm90bxoUTWVzc2FnZTJTZXJ2ZXIucHJvdG8y7gUKEEF2YWlsYWJsZVNlcnZp",
            "Y2USMwoNVHJ5Q29ubmVjdGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJvdG9i",
            "dWYuQm9vbFJlcxI9CglBZGRQbGF5ZXISEy5wcm90b2J1Zi5QbGF5ZXJNc2ca",
            "GS5wcm90b2J1Zi5NZXNzYWdlVG9DbGllbnQwARI3CgZHZXRNYXASFS5wcm90",
            "b2J1Zi5OdWxsUmVxdWVzdBoWLnByb3RvYnVmLk1lc3NhZ2VPZk1hcBIsCgRN",
            "b3ZlEhEucHJvdG9idWYuTW92ZU1zZxoRLnByb3RvYnVmLk1vdmVSZXMSLQoH",
            "UmVjb3ZlchIPLnByb3RvYnVmLklETXNnGhEucHJvdG9idWYuQm9vbFJlcxIt",
            "CgdQcm9kdWNlEg8ucHJvdG9idWYuSURNc2caES5wcm90b2J1Zi5Cb29sUmVz",
            "EjQKB1JlYnVpbGQSFi5wcm90b2J1Zi5Db25zdHJ1Y3RNc2caES5wcm90b2J1",
            "Zi5Cb29sUmVzEjYKCUNvbnN0cnVjdBIWLnByb3RvYnVmLkNvbnN0cnVjdE1z",
            "ZxoRLnByb3RvYnVmLkJvb2xSZXMSMAoGQXR0YWNrEhMucHJvdG9idWYuQXR0",
            "YWNrTXNnGhEucHJvdG9idWYuQm9vbFJlcxIsCgRTZW5kEhEucHJvdG9idWYu",
            "U2VuZE1zZxoRLnByb3RvYnVmLkJvb2xSZXMSOAoNSW5zdGFsbE1vZHVsZRIU",
            "LnByb3RvYnVmLkluc3RhbGxNc2caES5wcm90b2J1Zi5Cb29sUmVzEi0KB1Jl",
            "Y3ljbGUSDy5wcm90b2J1Zi5JRE1zZxoRLnByb3RvYnVmLkJvb2xSZXMSNgoJ",
            "QnVpbGRTaGlwEhYucHJvdG9idWYuQnVpbGRTaGlwTXNnGhEucHJvdG9idWYu",
            "Qm9vbFJlcxIyCgxFbmRBbGxBY3Rpb24SDy5wcm90b2J1Zi5JRE1zZxoRLnBy",
            "b3RvYnVmLkJvb2xSZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Message2ClientsReflection.Descriptor, global::Protobuf.Message2ServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
