using CommandLine;
using Grpc.Core;
using Preparation.Utility.Logging;
using Protobuf;

namespace Server
{
    public class Program
    {
        /// <summary>
        /// Generated by http://www.network-science.de/ascii/ with font "standard"
        /// </summary>
        const string welcome = """
                    ______________ ___  ____ ___  _____  .____________ 
                    \__    ___/   |   \|    |   \/  _  \ |   \______  \
                      |    | /    ~    \    |   /  /_\  \|   |   /    /
                      |    | \    Y    /    |  /    |    \   |  /    / 
                      |____|  \___|_  /|______/\____|__  /___| /____/  
                                    \/                 \/ 
                    _________ __                  __      __               
                    /   _____//  |______ _______  /  \    /  \_____ _______ 
                    \_____  \\   __\__  \\_  __ \ \   \/\/   /\__  \\_  __ \
                    /        \|  |  / __ \|  | \/  \        /  / __ \|  | \/
                  /_______  /|__| (____  /__|      \__/\  /  (____  /__|   
                          \/           \/               \/        \/    
        """;

        static (ServerBase, Logger) CreateServer(ArgumentOptions options)
            => options.Playback ? (new PlaybackServer(options), PlaybackServerLogging.logger)
                                : (new GameServer(options), GameServerLogging.logger);

        static int Main(string[] args)
        {
            string args_str = "";
            foreach (var arg in args)
                args_str += arg + " ";
            Logger.RawConsoleLog(args_str);

            ArgumentOptions? options = null;
            _ = Parser.Default.ParseArguments<ArgumentOptions>(args).WithParsed(o => { options = o; });
            if (options == null)
            {
                Logger.RawConsoleLog("Argument parsing failed!");
                return 1;
            }

            if (options.StartLockFile == "114514")
            {
                Logger.RawConsoleLog(welcome, false);
            }
            Logger.RawConsoleLog($"Server begins to run: {options.ServerPort}");

            try
            {
                var (server, logger) = CreateServer(options);
                Grpc.Core.Server rpcServer = new([new ChannelOption(ChannelOptions.SoReuseport, 0)])
                {
                    Services = { AvailableService.BindService(server) },
                    Ports = { new ServerPort(options.ServerIP, options.ServerPort, ServerCredentials.Insecure) }
                };
                rpcServer.Start();

                logger.ConsoleLog("Server begins to listen!");
                server.WaitForEnd();
                logger.ConsoleLog("Server end!");
                rpcServer.ShutdownAsync().Wait();

                Thread.Sleep(50);
                Logger.RawConsoleLog("", false);
                logger.ConsoleLog("===================  Final Score  ====================", false);
                logger.ConsoleLog($"Team0: {server.GetScore()[0]}"); //红队
                logger.ConsoleLog($"Team1: {server.GetScore()[1]}"); //蓝队
            }
            catch (Exception ex)
            {
                Logger.RawConsoleLog(ex.ToString());
                if (ex.StackTrace is not null)
                    Logger.RawConsoleLog(ex.StackTrace);
            }
            return 0;
        }
    }
}
