from argparse import ArgumentParser
import platform
import os
import sys
import multiprocessing as mp

sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))) + "/proto")

from PyAPI.ProcessEnv import ProcessEnv  # NOQA: E402
import PyAPI.structures as THUAI7  # NOQA: E402
from PyAPI.logic import Logic  # NOQA: E402
from PyAPI.AI import AI  # NOQA: E402


def PrintWelcomeString() -> None:
    # Generated by http://www.network-science.de/ascii/ with font "standard"
    welcomeString = r"""
            ______________ ___  ____ ___  _____  .____________
            \__    ___/   |   \|    |   \/  _  \ |   \______  \
              |    | /    ~    \    |   /  /_\  \|   |   /    /
              |    | \    Y    /    |  /    |    \   |  /    /
              |____|  \___|_  /|______/\____|__  /___| /____/
                            \/                 \/
            _________ __                  __      __
            /   _____//  |______ _______  /  \    /  \_____ _______
            \_____  \\   __\__  \\_  __ \ \   \/\/   /\__  \\_  __ \
            /        \|  |  / __ \|  | \/  \        /  / __ \|  | \/
           /_______  /|__| (____  /__|      \__/\  /  (____  /__|
                   \/           \/               \/        \/
    """
    print(welcomeString)


parser = ArgumentParser(
    description="THUAI7 Python Interface Commandline Parameter Introduction"
)
parser.add_argument(
    "-I",
    type=str,
    required=True,
    help="Server`s IP 127.0.0.1 in default",
    dest="sIP",
    default="127.0.0.1",
)
parser.add_argument(
    "-P",
    type=str,
    required=True,
    help="Server`s Port 8888 in default",
    dest="sPort",
    default="8888",
)
parser.add_argument(
    "-t",
    type=int,
    required=True,
    help="Team`s ID",
    dest="tID",
    choices=[0, 1],
)
parser.add_argument(
    "-d",
    action="store_true",
    help="Set this flag to save the debug log to ./logs folder",
    dest="file",
)
parser.add_argument(
    "-o",
    action="store_true",
    help="Set this flag to print the debug log to the screen",
    dest="screen",
)
parser.add_argument(
    "-w",
    action="store_true",
    help="Set this flag to only print warning on the screen",
    dest="warnOnly",
)


def StartLogic(pID: int,
               playerType: THUAI7.PlayerType,
               shipType: THUAI7.ShipType) -> None:
    processEnv = ProcessEnv()
    logic = Logic(pID, processEnv.tID, playerType, shipType, processEnv, StartLogic)
    logic.Main(lambda pID: AI(pID))


if __name__ == "__main__":
    args = parser.parse_args()

    if platform.system().lower() == "windows":
        PrintWelcomeString()

    processEnv = ProcessEnv(args.tID,
                            args.sIP, args.sPort,
                            args.file, args.screen, args.warnOnly)
    teamProcess = mp.Process(target=StartLogic,
                             args=(0, THUAI7.PlayerType.Team, THUAI7.ShipType.NullShipType))
    teamProcess.start()
    mp.Process(target=StartLogic,
               args=(1, THUAI7.PlayerType.Ship, THUAI7.ShipType.CivilianShip)).start()
    teamProcess.join()
