FROM mcr.microsoft.com/dotnet/sdk:8.0.300-jammy-amd64 AS build
LABEL maintainer="eesast"
WORKDIR /usr/local
COPY . .

FROM eesast/thuai7_base:base
LABEL maintainer="eesast"
WORKDIR /usr/local
RUN mkdir /usr/local/team1 && mkdir /usr/local/team2 && mkdir /usr/local/playback
COPY ./dependency/shell/run.sh .
COPY ./CAPI/python /usr/local/PlayerCode/CAPI/python
COPY ./dependency/proto /usr/local/PlayerCode/dependency/proto
COPY ./dependency/shell /usr/local/PlayerCode/dependency/shell
WORKDIR /usr/local/PlayerCode/CAPI/python
RUN bash ../../dependency/shell/generate_proto.sh

WORKDIR /usr/local
RUN export TERMINAL=CLIENT
ENTRYPOINT [ "bash","./run.sh" ]