// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from Services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for Services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5TZXJ2aWNlcy5wcm90bxIIcHJvdG9idWYaFU1lc3NhZ2UyQ2xpZW50cy5w",
            "cm90bxoUTWVzc2FnZTJTZXJ2ZXIucHJvdG8yswYKEEF2YWlsYWJsZVNlcnZp",
            "Y2USMwoNVHJ5Q29ubmVjdGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJvdG9i",
            "dWYuQm9vbFJlcxI9CglBZGRQbGF5ZXISEy5wcm90b2J1Zi5QbGF5ZXJNc2ca",
            "GS5wcm90b2J1Zi5NZXNzYWdlVG9DbGllbnQwARI3CgZHZXRNYXASFS5wcm90",
            "b2J1Zi5OdWxsUmVxdWVzdBoWLnByb3RvYnVmLk1lc3NhZ2VPZk1hcBIsCgRN",
            "b3ZlEhEucHJvdG9idWYuTW92ZU1zZxoRLnByb3RvYnVmLk1vdmVSZXMSMgoH",
            "UmVjb3ZlchIULnByb3RvYnVmLlJlY292ZXJNc2caES5wcm90b2J1Zi5Cb29s",
            "UmVzEi0KB1Byb2R1Y2USDy5wcm90b2J1Zi5JRE1zZxoRLnByb3RvYnVmLkJv",
            "b2xSZXMSNAoHUmVidWlsZBIWLnByb3RvYnVmLkNvbnN0cnVjdE1zZxoRLnBy",
            "b3RvYnVmLkJvb2xSZXMSNgoJQ29uc3RydWN0EhYucHJvdG9idWYuQ29uc3Ry",
            "dWN0TXNnGhEucHJvdG9idWYuQm9vbFJlcxIwCgZBdHRhY2sSEy5wcm90b2J1",
            "Zi5BdHRhY2tNc2caES5wcm90b2J1Zi5Cb29sUmVzEiwKBFNlbmQSES5wcm90",
            "b2J1Zi5TZW5kTXNnGhEucHJvdG9idWYuQm9vbFJlcxI4Cg1JbnN0YWxsTW9k",
            "dWxlEhQucHJvdG9idWYuSW5zdGFsbE1zZxoRLnByb3RvYnVmLkJvb2xSZXMS",
            "LQoHUmVjeWNsZRIPLnByb3RvYnVmLklETXNnGhEucHJvdG9idWYuQm9vbFJl",
            "cxI2CglCdWlsZFNoaXASFi5wcm90b2J1Zi5CdWlsZFNoaXBNc2caES5wcm90",
            "b2J1Zi5Cb29sUmVzEj4KDEJ1aWxkU2hpcFJJRBIWLnByb3RvYnVmLkJ1aWxk",
            "U2hpcE1zZxoWLnByb3RvYnVmLkJ1aWxkU2hpcFJlcxIyCgxFbmRBbGxBY3Rp",
            "b24SDy5wcm90b2J1Zi5JRE1zZxoRLnByb3RvYnVmLkJvb2xSZXNiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Message2ClientsReflection.Descriptor, global::Protobuf.Message2ServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
