name: deploy
on:
  push:
    branches: [dev, main, master]
  pull_request:
    branches: [dev, main, master]

env:
  version: 1.1.0.0

jobs:
  deploy-to-tencent-cos:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup dotnet-script
      run: dotnet tool install --global dotnet-script
    - name: Pre-Process
      run: dotnet script .github/preProcess/MauiEnvConfig.csx
    - name: Install Workloads
      run: dotnet workload install maui-windows
    - name: Create Folders need
      run: |
        mkdir D:\a\installer
        mkdir D:\a\publish
    - name: Copy THUAI7
      run: Copy-Item -recurse D:\a\THUAI7\THUAI7\ D:\a\mirror\
    - name: Test
      run: tree D:\a\mirror
    - name: Remove directories not needed
      run: |
        Remove-Item -recurse -force D:\a\mirror\.git
        Remove-Item -recurse D:\a\mirror\.github
        Remove-Item -recurse D:\a\mirror\installer
        Remove-Item -recurse D:\a\mirror\interface
        Remove-Item -recurse D:\a\mirror\logic
    - name: Build Server
      run: |
        mkdir D:\a\mirror\logic
        dotnet build "./logic/Server/Server.csproj" -o "D:\a\mirror\logic\Server" -p:WindowsAppSDKSelfContained=true -c Release
    - name: Build Client
      run: dotnet publish "./logic/Client/Client.csproj" -o "D:\a\mirror\logic\Client" -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true
    - name: Deploy to bucket
      run: dotnet run --project "./dependency/deploy/deploy.csproj" ${{ secrets.INSTALLER_COS_SECRET_ID }} ${{ secrets.INSTALLER_COS_SECRET_KEY }}
    - name: Get installer package(No Key contained for safety)
      run: |
        $version=Get-ChildItem -Path D:\a\publish | ForEach-Object { $_.name }
        [Environment]::SetEnvironmentVariable("version", $version, "Machine")
        dotnet publish "./installer/installer.csproj" -o "D:\a\installer" -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true
        ./dependency/7z/7za.exe a -r D:\a\publish\Installer_v${version}.zip D:\a\installer\*
    - name: Upload installer package
      uses: actions/upload-artifact@v4
      with:
        name: Installer_v${{ env.version }}.zip
        path: D:\a\publish\Installer_v${{ env.version }}.zip
