name: format
on:
  push:
    branches: [dev, main, master]
  pull_request:
    branches: [dev, main, master]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: '.'
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx,i,ixx,ipp,i++'
        clangFormatVersion: 14
        exclude: './players'
        inplace: False

  dotnet-format-checking-logic:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Check Logic
      run: |
        dotnet restore "./logic/logic.sln"
        dotnet format "./logic/logic.sln" --severity error --no-restore --verify-no-changes

  dotnet-format-checking-installer:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Check Installer
      run: |
        dotnet restore "./installer/installer.sln"
        dotnet format "./installer/installer.sln" --severity error --no-restore --verify-no-changes

  dotnet-format-checking-launcher:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Check Launcher
      run: |
        dotnet restore "./launcher/launcher.sln"
        dotnet format "./launcher/launcher.sln" --severity error --no-restore --verify-no-changes

  dotnet-format-checking-interface:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Check Interface
      run: |
        dotnet format whitespace "./interface/interface_live/Assets/Scripts/" --folder --verify-no-changes
        dotnet format whitespace "./interface/interface_playback/Assets/Scripts/" --folder --verify-no-changes
        dotnet format whitespace "./interface/interface_local/Assets/Scripts/" --folder --verify-no-changes